### ISSUE TITLE
computing the average precision for cityscapes

### ISSUE THREAD

**Issue by IssamLaradji** [imatge-upc/rsis#2]
Does the `eval_cityscapes.py` script compute the average precision for cityscapes results ?

**Comment by miriambellver** [comment]
Hi,

The eval_cityscapes.py generates the results to be evaluated for cityscapes. To obtain the average precision for cityscapes, you should use the official evaluation code in https://github.com/mcordts/cityscapesScripts, and point to the folder where your results are saved.

Regards,

Miriam
